### ISSUE TITLE
v2 format does not handle `Dictionary<_, LargeString>`

### ISSUE THREAD

**Issue by westonpace** [lance-format/lance#2828]
An error is thrown:

```
thread 'lance_background_thread' panicked at /home/pace/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-buffer-52.2.0/src/buffer/immutable.rs:222:9:
the offset of the new Buffer cannot exceed the existing length
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'lance_background_thread' panicked at /home/pace/dev/lance/rust/lance-encoding/src/decoder.rs:1267:65:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(74), ...)
```

**Comment by benmayersohn** [comment]
Was just about to open a ticket for this, glad you noticed it first! 😃
