### ISSUE TITLE
Lance v2.1 panic when do write read round for string datatype

### ISSUE THREAD

**Issue by broccoliSpicy** [lance-format/lance#2939]
lance commit: 7cc14d9dd19de9c5bdb9b0f9e6007ea0fd2c828d
error:
```
(venv) ➜  python git:(main) ✗ python ../test.py 
thread 'lance_background_thread' panicked at /home/admin/test_part_plain_non_numeric_panic/rust/lance-encoding/src/encodings/physical/fixed_size_binary.rs:87:9:
assertion `left == right` failed
  left: 112
 right: 8
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'lance_background_thread' panicked at /home/admin/test_part_plain_non_numeric_panic/rust/lance-encoding/src/encodings/physical/fixed_size_binary.rs:87:9:
assertion `left == right` failed
  left: 64
 right: 8
thread '<unnamed>' panicked at /home/admin/test_part_plain_non_numeric_panic/rust/lance-encoding/src/encodings/physical/dictionary.rs:113:44:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(41), "assertion `left == right` failed\n  left: 64\n right: 8", ...)
thread '<unnamed>' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x7fc7921af7ea - std::backtrace_rs::backtrace::libunwind::trace::h6b3b851d56c35d6f
                               at /rustc/0ee7cb5e3633502d9a90a85c3c367eccd59a0aba/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x7fc7921af7ea - std::backtrace_rs::backtrace::trace_unsynchronized::h36d27b2370c43ac4
                               at /rustc/0ee7cb5e3633502d9a90a85c3c367eccd59a0aba/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fc7921af7ea - std::sys::backtrace::_print_fmt::hff494ee3ee990e5f
                               at /rustc/0ee7cb5e3633502d9a90a85c3c367eccd59a0aba/library/std/src/sys/backtrace.rs:66:9
   3:     0x7fc7921af7ea - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h491f9ade7b8e0a95
                               at /rustc/0ee7cb5e3633502d9a90a85c3c367eccd59a0aba/library/std/src/sys/backtrace.rs:39:26
   4:     0x7fc7921ddcbb - core::fmt::rt::Argument::fmt::h411fecefb47b21ee
                               at /rustc/0ee7cb5e3633502d9a90a85c3c367eccd59a0aba/library/core/src/fmt/rt.rs:177:76
   5:     0x7fc7921ddcbb - core::fmt::write::h2afcec9c69a07a11
                               at /rustc/0ee7cb5e3633502d9a90a85c3c367eccd59a0aba/library/core/src/fmt/mod.rs:1178:21
   6:     0x7fc7921ab3e3 - std::io::Write::write_fmt::hf646430d56c9131b
                               at /rustc/0ee7cb5e3633502d9a90a85c3c367eccd59a0aba/library/std/src/io/mod.rs:1823:15
   7:     0x7fc7921af632 - std::sys::backtrace::BacktraceLock::print::hdf442cc2da5cdaa7
                               at /rustc/0ee7cb5e3633502d9a90a85c3c367eccd59a0aba/library/std/src/sys/backtrace.rs:42:9
   8:     0x7fc7921b0a37 - std::panicking::default_hook::{{closure}}::hdef449ccae551d59
                               at /rustc/0ee7cb5e3633502d9a90a85c3c367eccd59a0aba/library/std/src/panicking.rs:268:22
   9:     0x7fc7921b0866 - std::panicking::default_hook::h63c0d234407c6eb5
                               at /rustc/0ee7cb5e3633502d9a90a85c3c367eccd59a0aba/library/std/src/panicking.rs:295:9
  10:     0x7fc7921b1077 - std::panicking::rust_panic_with_hook::ha6cfc51100acb1ab
                               at /rustc/0ee7cb5e3633502d9a90a85c3c367eccd59a0aba/library/std/src/panicking.rs:801:13
  11:     0x7fc7921b0ee3 - std::panicking::begin_panic_handler::{{closure}}::he56e1efe5ba67ce1
                               at /rustc/0ee7cb5e3633502d9a90a85c3c367eccd59a0aba/library/std/src/panicking.rs:667:13
  12:     0x7fc7921afcc9 - std::sys::backtrace::__rust_end_short_backtrace::hcc7bf1345a5f7ae3
                               at /rustc/0ee7cb5e3633502d9a90a85c3c367eccd59a0aba/library/std/src/sys/backtrace.rs:170:18
  13:     0x7fc7921b0ba4 - rust_begin_unwind
                               at /rustc/0ee7cb5e3633502d9a90a85c3c367eccd59a0aba/library/std/src/panicking.rs:665:5
  14:     0x7fc7921dace5 - core::panicking::panic_nounwind_fmt::runtime::hb301b0c6b182a870
                               at /rustc/0ee7cb5e3633502d9a90a85c3c367eccd59a0aba/library/core/src/panicking.rs:112:18
  15:     0x7fc7921dace5 - core::panicking::panic_nounwind_fmt::ha0f665a7c186191d
                               at /rustc/0ee7cb5e3633502d9a90a85c3c367eccd59a0aba/library/core/src/panicking.rs:122:5
  16:     0x7fc7921dad72 - core::panicking::panic_nounwind::h687197fce896f829
                               at /rustc/0ee7cb5e3633502d9a90a85c3c367eccd59a0aba/library/core/src/panicking.rs:221:5
  17:     0x7fc7921daf36 - core::panicking::panic_cannot_unwind::h676ba4d44c5f79de
                               at /rustc/0ee7cb5e3633502d9a90a85c3c367eccd59a0aba/library/core/src/panicking.rs:310:5
  18:     0x7fc791f93d2c - arrow_array::ffi_stream::get_next::h78314459d4cdeaf7
                               at /home/admin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-array-52.2.0/src/ffi_stream.rs:133:1
  19:     0x7fc7c44403f3 - _ZN5arrow12_GLOBAL__N_122ArrayStreamBatchReaderILb0EE8ReadNextEPSt10shared_ptrINS_11RecordBatchEE
  20:     0x7fc7c85dfbc7 - _ZL59__pyx_pw_7pyarrow_3lib_17RecordBatchReader_7read_next_batchP7_objectPKS0_lS0_
  21:     0x7fc7c8532fa8 - _ZL52__pyx_pf_7pyarrow_3lib_17RecordBatchReader_4__next__P41__pyx_obj_7pyarrow_3lib_RecordBatchReader
  22:           0x52be92 - _PyEval_EvalFrameDefault
  23:           0x523d6b - PyEval_EvalCode
  24:           0x64a387 - <unknown>
  25:           0x647c4f - <unknown>
  26:           0x6537f0 - <unknown>
  27:           0x65353b - _PyRun_SimpleFileObject
  28:           0x653364 - _PyRun_AnyFileObject
  29:           0x6520ef - Py_RunMain
  30:           0x62a217 - Py_BytesMain
  31:     0x7fc7c8bec24a - <unknown>
  32:     0x7fc7c8bec305 - __libc_start_main
  33:           0x62a0b1 - _start
  34:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
[1]    851855 IOT instruction  python3 ../test.py
```
to reproduce:
```python
import os

import pyarrow as pa
import pyarrow.dataset as ds
import pyarrow.parquet as pq
from lance.file import LanceFileReader, LanceFileWriter

import duckdb
import pyarrow.parquet as pq

con = duckdb.connect(database=":memory:")
con.execute("INSTALL tpch; LOAD tpch")
con.execute("CALL dbgen(sf=1)")

parquet_path = "/tmp/parquet_ds.parquet"

tpch_dir_path = "/tmp/TPCH_SF1/"

tables = ["part"]

for t in tables:
    res = con.query("SELECT * FROM " + t)
    pq.write_table(res.to_arrow_table(), tpch_dir_path + t + ".parquet")

PATH = tpch_dir_path + tables[0] + ".parquet"

orig_dataset = ds.dataset(PATH)
orig_schema = orig_dataset.schema

target_types = [pa.string()]

target_columns = [
        field.name for field in orig_schema if field.type in target_types
]

table = orig_dataset.to_table(columns = target_columns)

lance_path = "/tmp/tpch.lance"

if os.path.exists(lance_path):
    if os.path.isdir(lance_path):
        shutil.rmtree(lance_path)
    else:
        os.remove(lance_path)

lance_version = "2.1"

with LanceFileWriter(lance_path, table.schema, version = lance_version) as writer:
    for batch in table.to_batches():
        writer.write_batch(batch)

batch_size = 8 * 1024

reader = LanceFileReader(lance_path)
for batch in reader.read_all(batch_size=batch_size).to_batches():
    pass

print("write read success")

```

**Comment by Xuanwo** [comment]
Closing this as stale due to substantial code drift. The fixed-size-binary decoder assertion implicated by the report was changed, and the encoding implementation has since been substantially reorganized. The original reproduction was not revalidated against a current release, so this is not a claim that the panic was verified as fixed. @broccoliSpicy, please reopen this issue with an updated reproduction if it still occurs.
